name: Black Formatter Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install black
      - name: Run Black formatter check
        run: black --check .
      - name: Apply Black formatting changes
        run: black --write .
      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Black formatting changes
